### ISSUE TITLE
bugs) during harbor installation, ingress domain doesn't set from values.yml

### ISSUE THREAD

**Issue by myminseok** [tanzu-end-to-end/tap-workshop#63]
Hi,
issue1) I tried to follow the installation document. and ran into issues with the harbor installation script does not apply the `ingress.domain` value from`tap-workshop/install/values/values-example.yaml` file. but it creates `core.harbor.domain` instead.

issues2) harbor installation script doesn't recognize properly if `git.gitHubToken` value is not specified. it breaks proper yaml generations and break installation steps.
```
#@data/values
---
ingress:
  domain: <INGRESS-DOMAIN>
  contour_tls_namespace: eduk8s
  contour_tls_secret: eduk8s-cert-tls
harbor:
  adminPassword: Harbor12345
  diskSize: 50Gi
gitea:
  adminPassword: <PASSWORD>
registry:
  dockerhub: docker.io
git:
  account: tanzu-end-to-end
  branch: main
  #! Optionally, you can specify a Github token. This will be used by Harbor's Trivy scanner to avoid hitting rate limites
  #!   gitHubToken: <token>
```
